### ISSUE TITLE
Twitter ad campaigns

### ISSUE THREAD

**Issue by JosephOR** [jublonet/codebird-js#101]
Hey,
I just came across codebird-js, had a quick look and able to get timeline statuses quite easily, compared to some other libraries. The problem is I need to access twitter ad campaigns, and noticed that there is no methods in codebird.js to retrieve these. I know there is a codebird-php as well, so is there a version for retrieving ad campaign data.
here is the calls I need to make - https://dev.twitter.com/ads/reference/get/accounts/%3Aaccount_id/campaigns/%3Acampaign_id 

cheers,
joey

**Comment by jublo** [comment]
Hi Joey,

Thanks for your request on. Codebird does not currently support accessing the Ads API, but we may look into adding support for this soon!

**Comment by jublo** [comment]
Hi again @JosephOR,

This is out of scope for Codebird itself. We are looking whether to make available a separate library in JS and/or PHP for accessing the Twitter Ads API. What is your environment—JS or PHP?
