### ISSUE TITLE
Access-Control-Allow-Origin issue

### ISSUE THREAD

**Issue by mparker11** [jublonet/codebird-js#102]
Just started working on my website and started getting this error. 
![shot_150707_193917](https://cloud.githubusercontent.com/assets/825507/8561856/1b23a1b6-24e0-11e5-9e1b-807ca289aea3.png)

**Comment by mparker11** [comment]
Nevermind. A few minutes later is stopped.

**Comment by mparker11** [comment]
Issue came back

**Comment by jublo** [comment]
Does this still happen for you, @mparker11?

**Comment by mparker11** [comment]
From what I can tell, I haven't had any issues since. Thanks!

**Comment by jublo** [comment]
Thanks!
