### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by mohan-mon** [jublonet/codebird-js#103]
One of my clients is getting empty responses when making a call to "lists_statuses". 
So may I please know if there are any rate limits imposed by you which is making it to send empty responses.
App helps in alerting the user when there are new tweets from the given list in twitter.
I'm using list_id parameter which is given as params to request for new tweets after that id.

I can understand there are rate limits imposed by twitter and we are working way with in those limits but still we are getting empty responses (just this response is being printed in console when i try to print "[httpstatus: 200]" ) it is the same response which i get when it has no new tweets to show. So in simple terms it says there are no new tweets though there are few new tweets.

Thank you in advance for the help provided.

**Comment by jublo** [comment]
Hi @mohan-mon, we're not currently imposing our own rate limits on the proxy API besides the ones implemented by the Twitter API itself.

Can you record some of the requests, for example with [Fiddler](http://www.fiddler2.com/), and send us the recording?

Thanks!

**Comment by mohan-mon** [comment]
Thank you for responding. 
Sure, I will look into fiddler and try to record.I haven't used it anytime yet, but will try to go through it and record, It would be of great help if you could stated what/how i have to record, just 2 to 3 instructions would be of great help as i can manage to take it from there.

**Comment by jublo** [comment]
When starting Fiddler, recording starts automatically (it sets your browser proxy). For Firefox, get the Fiddler add-on. In the Fiddler options, enable HTTPS decryption, and import the root certificate. Then, run your Codebird page test. In Fiddler, you will see requests being made to api.jublo.net. Select all and export them. Afterwards, exit Fiddler to stop intercepting your web connections.

**Comment by mohan-mon** [comment]
Is it available even for chrome as extension as i have to use the tool through chrome.If so can you please state the instructions for chrome extension as well.

**Comment by jublo** [comment]
Chrome doesnt need any extension as Chrome uses the system proxy settings inherited from IE.

**Comment by mohan-mon** [comment]
Sorry for the delay in replying. We found that there was a problem with the network as it was fine from my system in India but was not working in client's system in USA. When he changed his network, it started working again (before the changing of network, everything was working fine on his system except this API calls).
As the problem is solved after network change, i'm closing this issue.

Thank you,
Mohan.
