### ISSUE TITLE
exception when no internet connection exist

### ISSUE THREAD

**Issue by fadaytak** [jublonet/codebird-js#105]
hi,

im using this library with titanium and works fine, but when im testing it without internet connection to make some alert for client saying that a something was happen and we cannot share actually ....

but the problem i can't catch any thing no error ... 

is the library get back error to call function ? some exemple to do this ?

    var result = {};
    var params = {
	    	screen_name: userName
		};
		try{
			codebird.__call("users_show", params, function(reply) {
					if(reply){
						result = reply;
					}					
					callback(result);
				}, false // this parameter required
			);
		}catch(e){
			Ti.API.error("Twitter >> getUserData | " + e.message);
			callback(result);
		}

cordially

**Comment by hamzaezzi** [comment]
you can add in codebird.js file this code

        // function called when an error occurs, including a timeout
		xml.onerror = function(e) {
			callback(null,null,e);
		};
		xml.timeout = 30000;  // in milliseconds


and when you call __call function you do like this

    codebird.__call("users_show", params, function(reply,rate,err) {
                if(err){
                      alert("err" + JSON.stringify(err));
                }
                if(reply){
                    result = reply;
                }                   
                callback(result);
            }, false // this parameter required
        );


hope help you

**Comment by fadaytak** [comment]
yes !!! thanks, works fine

**Comment by jublo** [comment]
Reopening this issue as this should be part of Codebird itself. @hamzaezzi Can you send a PR, please?

**Comment by hamzaezzi** [comment]
done

**Comment by jublo** [comment]
@hamzaezzi Please test in `develop` branch now.
