### ISSUE TITLE
Persist login after page reload (save token in cookie)

### ISSUE THREAD

**Issue by kvonspiczak** [jublonet/codebird-js#107]
Hi guys,

I tried saving the received tokens in cookies with the help of https://github.com/js-cookie/js-cookie .
I could not get it to work however. I'm a bit confused about the different kinds of tokens (access/request). I tried saving them separately and access them whenever needed. Every time I tried using the saved tokens, they were either already expired or incorrect. Can someone give me a hint?
The project I'm working on is about generating an image via PHP, which the user then posts on his twitter timeline. I got it to work by writing one function which now does the following:
1. call oauth_requestToken
2. call oauth_authorize
3. call oauth_accessToken
After these three steps, the callback is executed, which looks like this:
1. call media_upload
2. call statuses_update (attach uploaded img to status)

I don't want to call everything over and over again when it's not needed.

Thanks in advance
Kevin

**Comment by jublo** [comment]
Once you have a working access token + secret, cache them, for instance, using this small script:

```javascript
if (typeof localStorage !== 'undefined') {
  localStorage.twitter = {
    access_token: access_token,
    access_token_secret: access_token_secret
  };
}
```

Next time the visitor comes and loads the page, just check if you have an access token in the localStorage, and use it right away without authenticating:

```javascript
var need_authentication = true,
  access_token = null,
  access_token_secret = null;

if (typeof localStorage !== 'undefined'
  && typeof localStorage.twitter !== 'undefined'
) {
  need_authentication = false;
  access_token        = localStorage.twitter.access_token;
  access_token_secret = localStorage.twitter.access_token_secret;
}
```

When calling media_upload then, I'd watch for httpstatus 401, which would mean the user has revoked the access to your app in the meantime.

Does this work for you?

**Comment by kvonspiczak** [comment]
I can't get it to work this way. The thing that confuses me the most is that one time you call setToken with request token as params, and the other time you call it with access token as params. I'm trying to split my logic into smaller pieces, so that I can call authorize, getRequestToken or whatever is needed when the user clicks on my share button. Right now I check the localStorage, if my cached values aren't in it, I call "oauth_requestToken" where I call setToken with the reply oauth_token, then I call "oauth_authorize", then I call "oauth_accessToken" if httpStatus is 200 I cache it plus I pass it to setToken again.. On page reload I check if I already have a token in localStorage.. if I find an access token there I call media_upload.. which tells me 401 could not authorize you..

**Comment by jublo** [comment]
Hi Kevin, 
Thanks for the detailed explanation of your app logic. 

Two things that I noticed:

1. You said that after the authentication flow, you call setToken with the access token and its secret. That is correct. But—are you calling setToken every time the page is loaded, so the access token is always set before calling media_upload? Otherwise, the access token will be in the localStorage, but Codebird won’t know about it just yet when trying to call the media/upload API.

2. How are you encoding the image data that you are sending to the media/upload endpoint?  Does your parameters array look somewhat like the following example, base-64 encoded JPG, GIF or PNG data?

```javascript
var params = {
    "media": "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAB+0lEQVR42mP8//8/Ay0BEwONwagFoxZQDljI0PP8x7/Z93/e+PxXmpMpXp5dh4+ZgYHh0bd/clxYnMuINaMtfvRLgp3RVZwVU+rkuz+eRz+//wXVxcrEkKnEceXTX0dRlhoNTmKDaOvzXwHHv6x9+gtN/M9/hpjTX+GmMzAw/P7HMOnOj+ff//35x/Ds+z9iLfjPwPDt7//QE1/Sz319/RNh3PkPf+58+Yup/t7Xf9p8zFKcTMRa4CLGCrFm1v2fSjs+pJ/7uuvl7w+//yO7HRkUq3GEyrCREMk+kqy2IiyH3/xhYGD48uf/rPs/Z93/yczIwM3CiFU9Hw5xnD4ouvTt4Tf0AP37n+HTb+w+UOBmIs2CICm2R9/+EZlqGRkYzIVYSLMgRIYtUYGdSAsMBFgUuJhIy2iMDAwt2pysjAwLHv78RcgnOcrs5BQVHEyMG579Imi6Nh9zrBxZFgixMW624pXnwldYcTAzLjDhZmUit7AzE2K54c7fp8eF1QhWRobFptwmgiwkF3b//jMwMjJ8+P3/zPs/yx/9Wvr412+MgBJlZ1xsyuOOrbAibMHH3/87b32fce/nR2ypnpuFMVGevU6TQ5SdqKKeEVez5cuf/7te/j727s+9L/++/v3PzcyowM1kIcTiLs7Kz8pIfNnOONouGrVg1AIGAJ6gvN4J6V9GAAAAAElFTkSuQmCC"
);
cb.__call(
    "media_upload",
    params,
    function (reply, rate, err) {
        // you get a media id back:
        console.log(reply.media_id_string);

        // call statuses_update here
    }
);
```

**Comment by kvonspiczak** [comment]
Hi jublo,

every page load (on user button click event) I call "oauth_requestToken" and store                 it ```codeBird.setToken(reply.oauth_token, reply.oauth_token_secret);```
then I call "oauth_authorize", wait for the user to enter the PIN and then I call "oauth_accessToken" and afterwards: ```codeBird.setToken(reply.oauth_token, reply.oauth_token_secret);``` again. 
To your 2nd question: yes my media params are just fine, they're also uploading correctly.
My problem is just about the persistence of these tokens. I'm confused because we have request and access tokens. Whenever I tried saving and restoring the access tokens from localStorage I couldn't get it to work because it was either expired or invalid. I'm just having a hard time understanding which way to go if I can't find a token available in localStorage on page load. For example, if I can not find a token saved already, I would have to call request_token, authorize, accessToken in this order, save the access token in localStorage and check on next page load again? If it's already in the localstorage on page load, I can skip the authorization and simply head over to the media upload part?

thanks in advance!
Kevin

**Comment by jublo** [comment]
Exactly, @kvonspiczak! Access tokens are valid for as long as the user that logged in didn't revoke access yet.

**Comment by kvonspiczak** [comment]
Okay so basically at the load of the page I would check my localStorage and see if I have a token + secret saved in there. If I already got these information, I'm going to try to upload the image, if this fails, the token is probably expired/invalid, so I'd request a new access token by requesting a new request token, let the user enter the pin etc.?

**Comment by jublo** [comment]
@kvonspiczak That’s right!

Find [more information about OAuth](https://dev.twitter.com/oauth/overview) on the Twitter website.
