### ISSUE TITLE
Not receiving new tweets when searching

### ISSUE THREAD

**Issue by filipjohansson** [jublonet/codebird-js#108]
As of today when I do a search I receive 15 tweets, I then fire the exact same search a while later and I receive the exact same tweets, even though there are new tweets when I do a regular search on https://twitter.com/search-home. It used to work just fine.

**Comment by jublo** [comment]
Hey @filipjohansson, this is probably because requests get cached, but you should get new data within 15 minutes.

Can you please confirm?

**Comment by filipjohansson** [comment]
I did seem to get new tweets after a while. I changed to my own proxy and that solved my problems. Is there a cache on your servers?

**Comment by jublo** [comment]
As I said:

> this is probably because requests get cached

Glad to hear you were able to resolve your issue!
