### ISSUE TITLE
Error processing your OAuth request: Invalid oauth_verifier parameter: null

### ISSUE THREAD

**Issue by nguyenhose** [jublonet/codebird-js#113]
Hi, I just use code bird to get access_token, but seem the examples does not work with this line 
```
      var query  = current_url.match(/\?(.+)$/).split("&amp;");
```
when my return url is 

```   
     http://localhost:3000/profile?oauth_token=PqJOrgAAAAAAjRPdAAABUbgFPJQ&oauth_verifier=4fjA8F2r7hBLvCTb1No7qd7Kqpq6a4Lg
```

So I decided to fix to 
```javascript      
     query = current_url.match(/\?(.+)$/)[1].split('&')
```
But seem when I call 
```javascript      
cb.__call 'oauth_accessToken', {oauth_verifier: parameters.oauth_verifier}, (reply, rate, err) ->
      if err
        console.log 'error response or timeout exceeded' + err.error
      if reply
        cb.setToken reply.oauth_token, reply.oauth_token_secret
      # if you need to persist the login after page reload,
      # consider storing the token in a cookie or HTML5 local storage
      return
```
I got the response 'Error processing your OAuth request: Invalid oauth_verifier parameter: null'
Any help will be appreciated, thank you.

**Comment by jublo** [comment]
What about this parsing function?

```coffeescript
getQueryParameter = (val) ->
  result = 'Not found'
  tmp = []
  items = location.search.substr(1).split('&')
  index = 0
  while index < items.length
    tmp = items[index].split('=')
    if tmp[0] == val
      result = decodeURIComponent(tmp[1])
    index++
  result

oauth_verifier = getQueryParameter('oauth_verifier')

cb.__call 'oauth_accessToken', { oauth_verifier: oauth_verifier }, (reply, rate, err) ->
      if err
        console.log 'error response or timeout exceeded' + err.error
      if reply
        cb.setToken reply.oauth_token, reply.oauth_token_secret
      # if you need to persist the login after page reload,
      # consider storing the token in a cookie or HTML5 local storage
      return
```

**Comment by nguyenhose** [comment]
hi @jublo , thank you for answer my question but my problem is after get oauth_verifier from url, I can't get access token with 'oauth_accessToken' function

**Comment by jublo** [comment]
@nguyenhose In your code, somehow the property `parameters.oauth_verifier` is not set. So, my code sample changes how the verifier is extracted from the query string parameters. Kindly give it a try and tell me the result.

**Comment by nguyenhose** [comment]
@jublo I did a try with your code with make sure it get 'oauth_verifier', and I received reply value on response :
```reply = Object {Diese Funktion ist vorübergehend nicht verfügbar: null, httpstatus: 401}

**Comment by jublo** [comment]
@nguyenhose This seems to be an upstream issue with the Twitter API. Also, you received an error message in German. Can you please retry to see if the error persists?

**Comment by nguyenhose** [comment]
Well, I always receive error message in German. I used PIN method for temporary.

**Comment by jublo** [comment]
@nguyenhose This does not seem to be anything related to Codebird itself. Please post your issue in the [Twitter Community Forums](https://twittercommunity.com/c/rest-api).

**Comment by apatharraj** [comment]
Hi Jublo

i Getting without pin method getting unauthorized error message only. So please share your working code.
