### ISSUE TITLE
Rate limit values are null

### ISSUE THREAD

**Issue by Vhati** [jublonet/codebird-js#115]
I'm using codebird 2.6.0 within an extension for Chrome 47.0.2526.106.

My method callbacks keep getting passed rate={limit:null, remaining:null, reset:null}.

At a glance, it seems that xml.getResponseHeader() isn't working.
Where xml = new window.XMLHttpRequest();

Something to do with origin policy?
http://stackoverflow.com/questions/7462968/restrictions-of-xmlhttprequests-getresponseheader

**Comment by Vhati** [comment]
I just inspected the network traffic in Chrome...

Request URL: https://api.jublo.net/codebird/1.1/account/verify_credentials.json

Relevant Response Headers...
Access-Control-Allow-Methods: POST, GET, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: X-Rate-Limit-Limit, X-Rate-Limit-Remaining, X-Rate-Limit-Reset
x-rate-limit-limit: 15
x-rate-limit-remaining: 14
x-rate-limit-reset: 1453052956

That all appears to be correct. Headers are case insensitive.

Re-enabled logging in my callback...
The problem went away on its own!?

I'll leave it up to you to decide whether this needs to be closed.
Is there a corner case that needs documenting, where Twitter sometimes omits the headers?

**Comment by jublo** [comment]
@Vhati The rate-limiting headers are important for users, yes.

Would you mind trying out the latest codebird.js from `develop` branch and see if it does anything better?
Can you provide a sample code that reproducibly returns `null` rate-limiting fields?

Thanks for helping to resolve this!

**Comment by Vhati** [comment]
Ah, I see what happened.

If non-string params are passed to codebird calls, it will break oauth.
Twitter won't send limit headers (callback will see a dict of null values).
There will be a reply, but one which includes an errors list.

Maybe codebird should test for that and throw an exception preemptively?

The following sample will demonstrate this in v2.6.0.
[test_null_limits.txt](https://github.com/jublonet/codebird-js/files/94707/test_null_limits.txt)

.

I was unable to test the develop branch, circa commit 290d288 , with Chrome 47.0.2526.106.

Uncaught TypeError: Cannot read property '_url' of undefined
 ^ g @ codebird.js:412
 ^ _http_build_query @ codebird.js:433
 ^ _callApi @ codebird.js:1391
 ^ __call @ codebird.js:1560
 ^ test @ background.js:20
 ^ (anonymous function) @ background.js:39

Line 412 reads...
> return this._url(c) + "=" + this._url(a);

I see that error even if I properly quote my parameters.

**Comment by jublo** [comment]
@Vhati Thanks for analysing that! Can you give me some samples of non-string parameters you tested & fails?

**Comment by Vhati** [comment]
Sorry about the delay, I had some hardware failures and projects distracting me.  ; )

> Can you give me some samples of non-string parameters you tested & fails?

There are only string, number, and boolean, right?

* Unquoted booleans fail - true and false - as shown in the code I linked above (friends/ids: stringify_ids).
* Unquoted numbers are okay. Both integers and floats (geo/search: max_results and latitude).

**Comment by Vhati** [comment]
On a related note, the "blocks/create" and "blocks/destroy" endpoints do not include rate headers in their response, even when successful.

And "application/rate_limit_status" only reports "blocks/ids" and "blocks/list".

The API docs say they *should* be limited.
https://dev.twitter.com/rest/reference/post/blocks/create
https://dev.twitter.com/rest/reference/post/blocks/destroy

**Comment by Vhati** [comment]
Okay, it seems "blocks/create" and "blocks/destroy" are unlimited.

In BlockTogether's source, actions.js says on [line 74](https://github.com/jsha/blocktogether/blob/7a19c7761022e585fc46d04ff443aba28b394bb4/actions.js#L74) ...
> Note that the block endpoint can only block one user at a time, but it does not appear to have a rate limit.

So a null rate can occur either on an oauth error OR endpoints which happen to have no limit.

**Comment by jublo** [comment]
Hello @Vhati,

Please also refer to the chart you find here: https://dev.twitter.com/rest/public/rate-limits.
Does this help you?

**Comment by jublo** [comment]
@Vhati Summarising, only this needs fixing?

> * Unquoted booleans fail - true and false - as shown in the code I linked above (friends/ids: stringify_ids).
* Unquoted numbers are okay. Both integers and floats (geo/search: max_results and latitude).

**Comment by Vhati** [comment]
Right, booleans are the problem. It could be framed either as a type coercion bug in codebird or a doc issue about quote necessity - depending on whether your policy is to coerce types or expect all strings.

A doc warning that null rates are possible, for unlimited endpoints, would be nice.

.
> also refer to the chart

Actually that chart is incomplete.
The "blocks/ids" endpoint IS limited but not listed.

However, that BlockTogether can create tens of thousands of blocks, one at a time, without delays is pretty solid evidence that "blocks/create" is not limited.  :P

**Comment by jublo** [comment]
@Vhati The rate limits table is definitely not complete due to the write limits not being defined there, they are per account. Twitter doesn’t document the block limit.

**Comment by jublo** [comment]
@Vhati I just tested this in Codebird 3.0.0-dev, and it works properly there.
