### ISSUE TITLE
Getting Bad Request 400

### ISSUE THREAD

**Issue by JonathanXXI** [jublonet/codebird-js#119]
I'm new to your Library, but I'm following steps as described on readme, but the issue is that I'm getting this error 

> POST https://api.jublo.net/codebird/oauth/request_token 400 (Bad Request)

 on console. I have checked I'm inputting correctly Consumer API Key and Secret, what could I do?

**Comment by jublo** [comment]
Hi Jonathan, which Codebird version are you using?

**Comment by jublo** [comment]
@JonathanXXI David, please follow up on this issue.

**Comment by JonathanXXI** [comment]
Sorry didn't get last notification, I've downloaded zip from this repository version 3.0.0-dev

**Comment by jublo** [comment]
Can you please post a complete sample code (leaving out the keys and secrets) up to the error?

**Comment by JonathanXXI** [comment]
Well this is like the example, I can't get passed from here

```
$('#twt-login').click(function (e) {
    $('#fb-login').addClass('disabled').off('click');
    $('#gplus-login').addClass('disabled').off('click');
    e.preventDefault();
    var cb = new Codebird;
    cb.setConsumerKey("xxxxxx", "xxxxxxx");
    cb.__call(
            "oauth_requestToken",
            {oauth_callback: "oob"},
    function (reply, rate, err) {//Don't know what value should have rate variable
        if (err) {
            console.log("error response or timeout exceeded" + err.error);
        }
        if (reply) {
            // stores it
            cb.setToken(reply.oauth_token, reply.oauth_token_secret);

            // gets the authorize screen URL
            cb.__call(
                    "oauth_authorize",
                    {},
                    function (auth_url) {
                        window.codebird_auth = window.open(auth_url);
                        //Window opens but without token GET parameter and get that error on console
                    }
            );
        }
    }
    );
});
```

**Comment by beebee1987** [comment]
Hi, is that any updated solutions? Im new to this library as well but I facing the same issue, hope to see is that any updated solution.

**Comment by Dimigergo** [comment]
I have the same issue with the code above. (example code is the same)

**Comment by JonathanXXI** [comment]
I switched to server side OAuth with PHP, and had to configure it to use proxy. My guess its that my previous workplace proxy blocked connections to jublo's API, I will try this again on a project using React, but try porting code to another computer out of proxy network.

**Comment by jublo** [comment]
@JonathanXXI Has this error appeared recently?

**Comment by jublo** [comment]
Closing this issue due to no further reply.
