### ISSUE TITLE
How do I pass to and execute a callback within a cb.__call?

### ISSUE THREAD

**Issue by jaegerbombb** [jublonet/codebird-js#120]
This is a beginner's javascript question. I'm struggling to understand how to call a function (functionA) outside of cb.__call, inside a cb.__call function?

**Comment by jaegerbombb** [comment]
Resolved

**Comment by MiguelDebruyne** [comment]
@jaegerbombb Please **always** provide the solution if you answer your own question so other people who are having the same question as you have an answer as well.
