### ISSUE TITLE
215: "Bad Authentication data."

### ISSUE THREAD

**Issue by aelallam** [jublonet/codebird-js#122]
I am using the latest version of codebird. I have followed all the steps, however I still cant update my timeline. This is my code:

```
`<script type="text/javascript">
            var cb = new Codebird;
                cb.setConsumerKey("...");
                cb.setToken("....");

                cb.__call(
                        "statuses_update",
                        {status: "Whohoo, I just tweeted!"},
                        function (reply) {
                            console.log(reply);  
                        });
                console.log("hello");
        </script>`
```

The reply is as follows:
`Object {errors: Array[1], httpstatus: 200}
errors
:
Array[1]
0
:
Object
code
:
215
message
:
"Bad Authentication data."
__proto__
:
Object
length
:
1
__proto__
:
Array[0]
httpstatus
:
200
__proto__
:
Object`
My keys and tokens match. I do not know why its code 215. Any pointers?

**Comment by emanton** [comment]
I have this problem too..., help someone plz )

**Comment by rsflow** [comment]
I am having the same issue!

**Comment by Dimigergo** [comment]
I have the same issue. :(

**Comment by isteven** [comment]
Hi, 

Unfortunately I also have the same issue. The code is similar with the OP's

```javascript
var cb = new Codebird;
cb.setConsumerKey("...", "...");

cb.__call(
    "statuses_update",
    {status: "Whohoo, I just tweeted!"},
    function (reply) {
        console.log(reply);  
    }
);

Perhaps it's because we set the wrong consumer key? 

I'm new in this, what's the difference between consumer key & token?

**Comment by idl-asad** [comment]
Hi,
I was also facing same issue, but it starts working after I added true as fourth parameter.

```
 cb.__call(

    "search_tweets",
    params,
    function (reply) {
        // ...
    },**true**
);

```

**Comment by jublo** [comment]
@idl-asad Your solution works for `search/tweets`, since this method supports app-only auth, but it won't work for `statuses/update`.

@aelallam @emanton @aiflow @Dimigergo @isteven Could you please post a dump of the outgoing request—using Developer Tools?

@isteven The consumer key and secret identify your Twitter app—get them at apps.twitter.com. The access token and secret, on the other hand, identify a user that logged in to Twitter using your app.

**Comment by walkerdanny** [comment]
Hi,

I've just run in to this issue myself - has anyone found a workaround for `statuses/update` and `media/upload` yet?

**Comment by jublo** [comment]
@walkerdanny Can you please post the values you try to Tweet, so we could take a look and reproduce the issue?

**Comment by superjoefly** [comment]
I, too, am getting Bad Authentication data using the following curl command:

curl https://api.jublo.net/codebird/1.1/search/tweets.json?q=cats

response is:

{"errors":[{"code":215,"message":"Bad Authentication data."}]}
