### ISSUE TITLE
Webpack issue: "require function is used in a way in which dependencies cannot be statically extracted"

### ISSUE THREAD

**Issue by davidcalhoun** [jublonet/codebird-js#123]
Full error:
./~/codebird/codebird.js
Critical dependencies:
1238:15-22 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/codebird/codebird.js 1238:15-22

Looks like it's actually complaining about this line: https://github.com/jublonet/codebird-js/blob/develop/codebird.js#L550

**Comment by blamejen** [comment]
having a same issue. Can it be fixed?

**Comment by jublo** [comment]
Hi @davidcalhoun and @blamejen:

* What Webpack version are you using (1.10.x or 2.x)?
* Please tell us about your environment:
OSX 10.x / Linux / Windows 10

**Comment by davidcalhoun** [comment]
Webpack version: 1.13.1
Environment: OSX 10.11.6

Thanks for your help!

**Comment by jublo** [comment]
@davidcalhoun Would you mind re-testing with this commit, please?

**Comment by davidcalhoun** [comment]
Thanks!  I just cherry-picked from that commit and that error no longer pops up!  :)

I'm getting some different errors now about it not being able to resolve some modules (xmlhttprequest, rsvp, when).  Looks like they need to be added to codebird's package.json?

Thanks a ton for your help!

**Comment by jublo** [comment]
Codebird tries to make intelligent guesses as to which libraries are available on the system. In the `package.json` file, the `xmlhttprequest` package is listed in the `devDependencies` section. However, regarding `rsvp` and `when`: The `package.json` lists `q`, so when `q` is installed, you won’t need `rsvp` or `when`.

```
  "devDependencies": {
    "babel-cli": "^6.3.17",
    "babel-preset-es2015": "^6.3.13",
    "eslint": "^1.10.3",
    "faucet": "0.0.1",
    "q": "^1.4.1",
    "tape": "^4.4.0",
    "tape-promise": "^1.0.1",
    "xmlhttprequest": "^1.8.0"
  }
```

```javascript
      if (typeof require !== "undefined") {
        let promise_class = false;
        try {
          promise_class = require("jquery");
        } catch (e) { }
        if (promise_class) {
          return promise_class.Deferred();
        }
        try {
          promise_class = require("q");
        } catch (e) { }
        if (!promise_class) {
          try {
            promise_class = require("rsvp");
          } catch (e) { }
        }
        if (!promise_class) {
          try {
            promise_class = require("when");
          } catch (e) { }
        }
        if (promise_class) {
          try {
            return promise_class.defer();
          } catch (e) { }
        }
      }
```

**Comment by davidcalhoun** [comment]
Cool, that makes sense.  I think it's some strange thing Webpack is doing, looking at code paths that should never execute.

In any case, I think the original problem is solved.  Thanks again!

**Comment by jublo** [comment]
You're welcome, David!
