### ISSUE TITLE
Uploading media to Twitter

### ISSUE THREAD

**Issue by JulienLeal** [jublonet/codebird-js#124]
Hi, when I uploaded media to twitter, my response is 

```
{code: 32, message: "Could not authenticate you."}
```

follow my code

First I call the function LoginTwitter 

```
var cb = new Codebird;
cb.setConsumerKey("xxxxxxxxxxxxx", "xxxxxxxxxxxxx");

function LoginTwitter(){
   cb.__call(
        "oauth_requestToken",
        {oauth_callback: "oob"},
        function (reply,rate,err) {
            if (err) {
                console.log("error response or timeout exceeded" + err.error);
            }
            if (reply) {
                // stores it
                cb.setToken(reply.oauth_token, reply.oauth_token_secret);

                // gets the authorize screen URL
                cb.__call(
                    "oauth_authorize",
                    {},
                    function (auth_url) {
                        window.codebird_auth = window.open(auth_url);
                        pin();
                    }
                );
            }
        }
    );
}
```

Then, I show this popup.

```
function pin(){
    dialog = $( "#dialog-form" ).dialog({
        autoOpen: true,
        height: 150,
        width: 230,
        modal: true,
        buttons: {

            Send: function() {
                pinPost();
                dialog.dialog( "close" );
            }
        }
    });
}
```

 When the user get the pin, he copy and paste in dialog, and send, calling the pinPost method

```
function pinPost(){
    cb.__call(
        "oauth_accessToken",
        {oauth_verifier: document.getElementById("pin").value},
        function (reply,rate,err) {
            if (err) {
                console.log("error response or timeout exceeded" + err.error);
            }
            if (reply) {
                // store the authenticated token, which may be different from the request token (!)
                cb.setToken(reply.oauth_token, reply.oauth_token_secret);

               //I can post status but I can't post media
                /*cb.__call(
                    "statuses_update",
                    {"status": "Whohoo, I just tweeted!"},
                    function (reply, rate, err) {
                    }
                );*/
                var params = {
                    "media_data": dataURItoBlob($("#meme").memeGenerator("save"))
                };

                cb.__call(
                    "media_upload",
                    params,
                    function (reply, rate, err) {
                        // you get a media id back:
                        if(reply)
                            console.log(reply.media_id_string);
                        if (err) {
                            console.log("error response or timeout exceeded" + err.error);
                        }
                        // continue upload of 2nd image here, if any (just 1 image works, too!)
                    }
                );
            }
        }
    );
}
```

I don't understand why this error appear to me. The stranger is I can post status. I tested it. I even commented this part of post status my code that you can see it. 
Have idea why this error?

**Comment by jublo** [comment]
Are the data base-64?

**Comment by jublo** [comment]
@JulienLeal What does `dataURItoBlob($("#meme").memeGenerator("save")` return?

**Comment by JulienLeal** [comment]
dataURItoBlob return a media.I get the base64  and transform it in media. I do it because I use the same method in facebook. I know that twitter accept base64.
Sorry for my late, I was in Brazil JS Conference's and doesn't see github in last days

**Comment by jublo** [comment]
@JulienLeal Thanks for your reply. We'll take a look at base64-encoded media uploads. Can you send me a sample string that dataURItoBlob returns?

**Comment by JulienLeal** [comment]
''' "media_data": dataURItoBlob($("#meme").memeGenerator("save"))'''
dataURItoBlob returns a Blob with type of media. 
$("#meme").memeGenerator("save") return a base64.

**Comment by jublo** [comment]
`media_data` does not accept blobs, but accepts Base64-encoded data directly.
In the end, your code must be equivalent to this text:

    "media_data": "R0lGODlhPQBEAPeoAJosM//AwO/AwHVYZ/z595kzAP/s..."

Please note that the data URI headers are to be omitted.

Can you [try this version of codebird.js](https://github.com/jublonet/codebird-js/blob/c19ef95d8363afef63a82a000502e8de47762571/codebird.js) and see if it works for uploading base64 images?

**Comment by jublo** [comment]
@JulienLeal Have you had a chance to take a look at our post?

https://github.com/jublonet/codebird-js/issues/124#issuecomment-243858485

**Comment by zGrav** [comment]
@jublo can confirm that doesn't work.

**Comment by alanabi20** [comment]
Guys, this is still not working. Does anyone got a change to check it out and finds a way to solve that?

**Comment by jublo** [comment]
@alanabi20 @zGrav Could you link us to a (non-) working live demo of this so we can debug it, please?

**Comment by alanabi20** [comment]
@jublo  I have figured out my issue. I used a proxy hosted on my server which was not accepting large data (e.g. image file) as part of the HTTP request.

I solved it by using Codebird proxy only!

**Comment by jublo** [comment]
@alanabi20 Did you know? If your proxy is a PHP one, you can increase the settings `post_max_size` *and* `upload_max_filesize` and support larger uploads :)

https://secure.php.net/manual/ini.core.php
