### ISSUE TITLE
Posting replies only showing up as replies intermittently?

### ISSUE THREAD

**Issue by stevengoldberg** [jublonet/codebird-js#128]
I'm using codebird to build a Chrome extension that can automatically reply to tweets.

The `status` in my POST payload includes the username that I'm replying to, and I'm sending an `in_reply_to_status_id` key with the `id_str` of the tweet I'm replying to.

The tweets are being posted successfully. However, the tweets only seem to appear as threaded replies on my timeline intermittently -- other times they look like replies, but don't bring up the thread when clicked. The most recent tweet posted by the extension showed up as a threaded reply the first time I looked at it, a few minutes ago. Now when I go back to the same tweet, it no longer displays as a threaded reply.

When I look at the network response for the ones that don't display as threads, the returned tweet has the correct values for `in_reply_to_status_id_str`, `in_reply_to_screen_name`, and `in_reply_to_user_id_str`. When I inspect the non-threaded replies in the DOM, they also have the correct `data-conversation-id` for the tweet they should be replying to, `data-is-reply-to="true"` and `data-has-parent-tweet="true"`. In other words, they look exactly the same to me as the ones that *do* show up as threaded.

Is there something I'm missing here?

**Comment by jublo** [comment]
@stevengoldberg Have you found any additional information on this issue yet?

**Comment by stevengoldberg** [comment]
Hey, never got any real concrete info on what was causing it, but I'm nearly certain it had to do with Twitter -- possibly some overly aggressive spam filtering on their end. Feel free to close this issue.

**Comment by jublo** [comment]
@stevengoldberg Thanks for your feedback though. Much appreciated!
