### ISSUE TITLE
Authenticating using a callback URL, without PIN problem

### ISSUE THREAD

**Issue by mdeprezzo** [jublonet/codebird-js#130]
Hi guys,
i'm using codebird-js for an app build with F7 and Vuejs and Phonegap. I'm using the authentication on the title, but when i make the call to "oauth_authorize", the return URL doesn't have any **oauth_verifier**. Am i missing something ?

**Comment by mdeprezzo** [comment]
The problem was in callback url that i had setted.

**Comment by MiguelDebruyne** [comment]
@mdeprezzo Care to elaborate further how you fixed it? I'm having problems as well. Your answer could have been of help. Please, always do that when you solve your own question

**Comment by mdeprezzo** [comment]
Sure, later i'll post my solution

**Comment by apatharraj** [comment]
HI mdeprezzo ,

Please post your working code
