### ISSUE TITLE
Authentication in popup but return url to parent window after action

### ISSUE THREAD

**Issue by MiguelDebruyne** [jublonet/codebird-js#132]
When trying to authenticate a request token via `oauth_authorize` or `oauth_authenticate` a popup /new tab comes up for the user to confirm or decline. Problem is when the user does an action the app redirects the user back to the site on that same popup/tab. I need it to self close and return the url.

Problem is by creating a new window you lose the window pointer because the window redirects itself to twitter for authentication so trying to get the `window.location.url` doesn't work anymore because of `cross-origin` problems.

I could do it via PIN but that just seems like to much hassle for the user.

**Comment by MiguelDebruyne** [comment]
Yeah, probably my bad. I think the problem was because of the callback url. I was using localhost while I should have been using 127.0.0.1 as I have set in my Twitter app settings.

When Twitter redirects back to my app in the popup window I'm able to grab that window again in JS and close it.

**Comment by jublo** [comment]
So your issue is resolved?

**Comment by goug0702** [comment]
I met the same problem as you. Could you give me some hint on how to grab the window and close it? @MiguelDebruyne

**Comment by MiguelDebruyne** [comment]
@jublo Sorry didnt notice this, yes this is resolved.

@goug0702 It's been a while, but this was just plain Javascript window handling as far as I remember.

**Comment by mynetx** [comment]
@MiguelDebruyne Thank you for getting back to me on this. Much appreciated! :)
