### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by Mindbowser** [jublonet/codebird-js#136]
We are getting Bad Gateway error since couple of days, please let us know how to solve it.

**Comment by jeverd01** [comment]
I believe the proxy is broken see the ticket I just created - https://github.com/jublonet/codebird-cors-proxy/issues/8

**Comment by joshuaatkins** [comment]
Hi @Mindbowser, 

Thanks for reporting! We now appear to have brought the API to some stability. Although we will monitor over the next 48 hours. 

Josh
