### ISSUE TITLE
Caching messages

### ISSUE THREAD

**Issue by SansCostard** [jublonet/codebird-js#141]
Hi,

I'm using this wonderful library since few days now, and it seems like some results are cached.

I've deleted many messages from my twitter account, still, when i'm calling direct_messages i still saw them.
I've deleted them 10 days ago now, but they still appears in the json response.

Any ideas ?

Thanks

**Comment by SansCostard** [comment]
Well, it seems like it's on the twitter api side.
Looks like you cannot delete sent messages, this is really weird :/

**Comment by jublo** [comment]
@SansCostard Do they appear on twitter.com?

**Comment by SansCostard** [comment]
No.
