### ISSUE TITLE
Request to api.jublo.net/codebird/oauth2/token always canceled

### ISSUE THREAD

**Issue by svoltmer** [jublonet/codebird-js#147]
For three days now our company Twitter feed through your proxy is failing when requesting https://api.jublo.net/codebird/oauth2/token. The request is always canceled. We have not changed anything on our end. Please look into this and reply back as soon as possible. Thanks!

**Comment by joshuaatkins** [comment]
Hi @svoltmer this should now have been resolved. Let me know if you have any further issues.
