### ISSUE TITLE
Truncated Tweets Returned

### ISSUE THREAD

**Issue by kjanjua26** [jublonet/codebird-js#151]
The  `  client.__call(
            "search_tweets",
            params,
            function (reply, rate, err) {})
` works fine except that it returns truncated tweets. I read online that a solution is to set `tweet_mode= extended` to the url. However, I am not able to do this here. Any solution how to do this?

**Comment by jublo** [comment]
@kjanjua26 Try this:

```javascript
client.__call( "search_tweets", {tweet_mode: "extended"}, function (reply, rate, err) {})
```

Does that work?

**Comment by kjanjua26** [comment]
Hey, yeah that works. 
Thanks.
