### ISSUE TITLE
Runtime error when parsing error response from Twitter

### ISSUE THREAD

**Issue by araskin** [jublonet/codebird-js#156]
In the _parseAPIReply there is a run time error when parsing an XML response from Twitter. 
![pastedgraphic-1](https://user-images.githubusercontent.com/3648751/44911223-c360e780-aceb-11e8-85b2-0fd68c249382.png)

It seems that Twitter is responding slightly differently then what the RegEx is expecting and this is causing the call to match to return a null and not an array. Therefore the [1] causes a run time error.

Here is a screen shot of the reply variable. The code="415" is causing the issue.
![pastedgraphic-3](https://user-images.githubusercontent.com/3648751/44911309-0e7afa80-acec-11e8-93e8-d081e192f067.png)

**Comment by mynetx** [comment]
Hey @araskin, thanks for catching that! I’ll go and fix it right away. 😌

**Comment by mynetx** [comment]
@araskin Please test the version in https://github.com/jublonet/codebird-js/tree/405139e21ccee15777654eb0258159135ddda9aa – either codebird.es7.js or codebird.js, depending on your environment. Please let me know whether this works for you.

Here’s an example:

```javascript
// gets a request token
cb.__call("oauth_requestToken", { oauth_callback: "oob" }, function(
  reply,
  rate,
  err
) {
  if (err) {
    console.log("error response or timeout exceeded" + err.error);
  }
  if (reply) {
    if (reply.errors && reply.errors["415"]) {
      // check your callback URL
      console.log(reply.errors["415"]);
      return;
    }

    // stores the token
    cb.setToken(reply.oauth_token, reply.oauth_token_secret);

    // gets the authorize screen URL
    cb.__call("oauth_authorize", {}, function(auth_url) {
      window.codebird_auth = window.open(auth_url);
    });
  }
});
```
