### ISSUE TITLE
Issue with "user/profile_banner"

### ISSUE THREAD

**Issue by efegurkan07** [jublonet/codebird-js#158]
when I try to call "user_profile_banner", it is covnerted to "user/profile/banner" where it should  be "user/profile_banner".

I guess it is same with every request which has underscore. 

Error in render: "Can't find HTTP method to use for "users/profile/banner"."

**Comment by mynetx** [comment]
@efegurkan07 Can you try to call `user_profileBanner` instead?

Please note this passage of the documentation:

> 1. For each slash in a Twitter API method, use an underscore in the Codebird function.
> 
>    Example: `statuses/update` maps to `cb.__call("statuses_update", ...)`.
> 
> 2. For each underscore in a Twitter API method, use camelCase in the Codebird function.
> 
>    Example: `statuses/home_timeline` maps to `cb.__call("statuses_homeTimeline", ...)`.

Let me know if this helps :)

**Comment by efegurkan07** [comment]
Oh I didn't see that in the documentation :) It helps thanks!

**Comment by mynetx** [comment]
@efegurkan07 You're welcome. :)
