### ISSUE TITLE
No PIN authentication

### ISSUE THREAD

**Issue by sergeyd63** [jublonet/codebird-js#16]
How can i get an access token/secret after getting the oauth_token and oauth_verifier in callback url (http://mydomain?oauth_token=blah&oauth_verifier=blah). Trying to do it from your example but without PIN.
Thanks.

**Comment by hhammoud01** [comment]
Hey guys, anyone solved this issue ?
Thanks in advance.

**Comment by jublo** [comment]
Can anyone of you please provide us with a full simple sample that reproduces the bug described here?
