### ISSUE TITLE
Unretweet 

### ISSUE THREAD

**Issue by christinna9031** [jublonet/codebird-js#177]
Everything is working great, thank you for this great library! I just have one question, would it be possible to add "POST statuses/unretweet/:id"? It seems to be missing in the list. https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/post-statuses-unretweet-id 
 Thanks!

**Comment by lifeboatpres** [comment]
You can edit src/codebird.php and change 'statuses/retweet/:id', to

```
'statuses/retweet/:id',
'statuses/unretweet/:id', 
```

**Comment by christinna9031** [comment]
Thank you!
