### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by schmidtflo** [jublonet/codebird-js#26]
I would prefer a better documentation, also with completet but easy programming examples, like an easy website for a twitter stream of an user and with example tokens. So that everybody can copy&paste this website, replace the tokens and then run the website.

**Comment by jublo** [comment]
@schmidtflo Is having better documentation still a key issue for you?

**Comment by Vhati** [comment]
It may be helpful to have the readme explicitly say all parameters should be strings.

I was grappling with the mysterious "Could not authenticate you" error for a while before realizing this.
true != "true"

I added quotes, and my call to blocks_ids worked.

**Comment by Vhati** [comment]
From the commits, I gather "err.error" is for codebird exceptions, not present in 2.6.0.

The readme could benefit from an example simultaneously handling Twitter's "reply.errors[0].message" as well.

**Comment by jublo** [comment]
@Vhati In Codebird 3.0, unquoted boolean values should work properly.
