### ISSUE TITLE
statuses_userTimeline returning error "Failed to load resource  https://api.jublo.net/codebird/1.1/statuses/user_timeline.json?screen_name=adityapratap270&count=20

### ISSUE THREAD

**Issue by adityap-optimus** [jublonet/codebird-js#33]
statuses_userTimeline returning error "Failed to load resource  https://api.jublo.net/codebird/1.1/statuses/user_timeline.json?screen_name=adityapratap270&count=20

Also I tried  

objTwitterCB.__call(
        "oauth_requestToken",
        {oauth_callback: "oob"},
        function (reply) {
            // stores it
            objTwitterCB.setToken(reply.oauth_token, reply.oauth_token_secret);
              console.log(reply);
            // gets the authorize screen URL
            objTwitterCB.__call(
                "oauth_authorize",
                {},
                function (auth_url) {
                    window.codebird_auth = window.open(auth_url);
                }
            );
        }
    );

It returned an error :-1: 
Whoa there!
There is no request token for this page. That's the special key we need from applications asking to use your Twitter account. Please go back to the site or application that sent you here and try again; it was probably just a mistake.

**Comment by iKomettech** [comment]
GET https://api.jublo.net/codebird/1.1/statuses/user_timeline.json?id=xxxx&count=4&tweet_mode=extended 404

**Comment by iKomettech** [comment]
What is the solution for this issue @adityap-optimus

**Comment by iKomettech** [comment]
> Yes its working now, Thanks for responding.
> 
> Was it a server downtime issue??

What is the solution for this issue

**Comment by iKomettech** [comment]
> Yes its working now, Thanks for responding.
> 
> Was it a server downtime issue??

What is the solution for this issue
