### ISSUE TITLE
net::ERR_CONNECTION_TIMED_OUT https://api.jublo.net/codebird/oauth2/token

### ISSUE THREAD

**Issue by yesity** [jublonet/codebird-js#76]
I'm using codebird to get tweets using search API, it just stop working today, and I can see this error on the site Failed to load resource: net::ERR_CONNECTION_TIMED_OUT https://api.jublo.net/codebird/oauth2/token

is there any issue with proxy?

**Comment by Amiin29** [comment]
Hey my friend I have a question about the connection with server with the method rest api basic authentication help me please
