### ISSUE TITLE
Special oauth_ methods: Fix force_login parameter

### ISSUE THREAD

**Issue by rojobo** [jublonet/codebird-js#81]
on the codebird.js file line #590 has an error!! when authenticating in order for us to use the force login parameter there neeeds to be an "&" instead of a "?" otherwhise when setting this parameter to true it would not force login......!!!!

line #590            url += "?force_login=1";

change to....

line #590            url += "&force_login=1";

**Comment by rojobo** [comment]
@jublo ive been absent for I while as you guys can tell I was hoping that by the time I got back you guys would release update 2.6 but I just ran a bower update and the version is still 2.5 and this is still an issue. Any date on the next release>? thanks a bunch

**Comment by jublo** [comment]
Sorry @rojobo for the release delay. We will actively work on a release within a week. Does that suit you?
