### ISSUE TITLE
ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by mohan-mon** [jublonet/codebird-js#89]
when i'm making the requests, it is sending a timeout error. when i went to https://api.jublo.net/codebird/1.1/users/show.json  i found the server down.
Can someone help me understand if it is a temporary issue or it is permanently taken down..?

Thank you,
Mohan.

**Comment by inamalam** [comment]
I am also facing ERR_CONNECTION_TIMED_OUT issue for the call https://api.jublo.net/codebird/oauth/request_token seems like server is down.

Any update?

**Comment by mohan-mon** [comment]
Unfortunately its still the same. Just yesterday i accepted to do a project for my client keeping this in mind and today it stopped working!

**Comment by writeosahon** [comment]
@jublo PLEASE RESPOND TO this issue raised by @mohan-mon  and @inamalam . 
I am facing the same issue. The app I created suddenly stopped displaying tweets to my end-users.
Please kindly respond.

Thanks

**Comment by jublo** [comment]
Hi there,
Thank you all for reporting this issue. We're aware and working on a fix. Your client-side code does not need any fixes, as this issue is caused server-side.

**Comment by writeosahon** [comment]
@jublo Thank you, You are a life saver.!! :)  Please can you kindly post to this thread when the issue is fixed?
Thank you so much

**Comment by jublo** [comment]
@writeosahon You're welcome, Osahon. Our engineering department is currently heading over to the server rooms to take an extensive look at the wires.

**Comment by mohan-mon** [comment]
@jublo Please don't take me in wrong way, may i please know when can we expect it to be resolved and if this will be temporary or permanent fix..?and if this will stay live for at least an year or so..?Asking because, depending on that i have to  decision on whether i can go with this or not for my client project.

Thank you,
Mohn

**Comment by jublo** [comment]
@mohan-mon We have no plans to deprecate support for the public Codebird proxy. If you want to make sure your environment is unaffected, why not take a look into [setting up your own proxy](https://github.com/jublonet/codebird/cors/proxy)?

**Comment by joshuaatkins** [comment]
I have now managed to restore service on the Public API. We are going to continue to monitor the service overnight (UK time here 12:40am!) and review in the morning and add some additional redundancy. 

Please post if you start to experience anymore problems.

**Comment by inamalam** [comment]
Thanks guys it's working.

**Comment by mohan-mon** [comment]
Thanks a lot for the efforts put in to restore the service.
Its working now.
Thanks again to @joshuaatkins

**Comment by mohan-mon** [comment]
Sorry that i'm reopening it.
It is again giving timeout errors for any call.

Thank you in advance,
Mohan.
