### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by mohan-mon** [jublonet/codebird-js#90]
When i'm making the requests, I have been getting many 502 Bad Gateway responses lately.
Can you please check.

Thank you,
Mohan.

**Comment by jublo** [comment]
Thanks for notifying us, @mohan-mon. We will take a look ASAP.

**Comment by wbyoko** [comment]
:+1:

**Comment by graphical-iain** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by graphical-iain** [comment]
I have been getting this as well. Here's the output to my console in Chrome:

<pre><code>POST https://api.jublo.net/codebird/oauth2/token 
502 (Bad Gateway)  codebird.js:679
GET https://api.jublo.net/codebird/1.1/search/tweets.json?q=hashtag&count=10 
502 (Bad Gateway)  codebird.js:1425</code>
</pre>

**Comment by joshuaatkins** [comment]
Thanks for your patience, we have made some performance improvements to this and will monitor over the next few days.

Please let us know if you continue to have problems.

**Comment by mohan-mon** [comment]
Again I have been getting many 502 Bad Gateway responses.
Can you please check.

Thank you,
Mohan.

**Comment by joshuaatkins** [comment]
Hi @mohan, we have been informed by our data centre that there have been some network connectivity issues over today. 

Can you outline when you are receiving these errors?

**Comment by mohan-mon** [comment]
Hi @joshuaatkins , 
Sorry for the delay in replying.
It happened 14 hours ago.
My code was requesting for "lists_statuses" at the point of time.
Hope this helps.

**Comment by joshuaatkins** [comment]
hey @mohan-mon, our DC was conducting some emergency maintenance at that time. Can you confirm whether you are experiencing more of this?

**Comment by Juggernaut93** [comment]
@joshuaatkins I'm getting this error just now.

**Comment by graphical-iain** [comment]
I am as well, with the same console errors as I posted before.

**Comment by joshuaatkins** [comment]
Hi @graphical-iain, @Juggernaut93. Sorry! We had to make emergency maintenance on the server. We did fail over to our UK node - but DNS doesn't propagate that quickly!

This has now been resolved and service restored. 

We are currently in the process of creating a premium - more resilient API service with a distributed network of servers, but this isn't quite ready yet.

**Comment by mohan-mon** [comment]
Hi @joshuaatkins thank you for the response and restoring the service.
Hope you will retain the present service as free and create a premium service with more features/services added to it.Because for old projects which we have done long back, neither we can start charging old clients for whom we have built apps using this service long back nor we can pay it from our pockets for old projects.
Hope you understand.

**Comment by chrisxwan** [comment]
Hi @jublo and @joshuaatkins, I've been getting the 502 service error recently (it was working earlier today!) 

It's failing when I call 

```
cb.__call(
    "oauth2_token",
    {},
    function (reply) {
        var bearer_token = reply.access_token;
        console.log(bearer_token);
    }
);
```

Could you take a look? 

Thank you so much!

**Comment by jublo** [comment]
Thanks @chrisxwan for your report!  We will take a look at it.

**Comment by jublo** [comment]
Has this been resolved for you, @mohan-mon?

**Comment by mohan-mon** [comment]
@jublo thank you for asking, it is working fine.

**Comment by jublo** [comment]
Glad to hear!

**Comment by derekyangsolvay** [comment]
@jublo   it seems the 502 error coming back,  any idea?   thanks

**Comment by jublo** [comment]
Can you test again, @derekyangsolvay ?

**Comment by derekyangsolvay** [comment]
Yes, it working now,  thanks!

**Comment by derekyangsolvay** [comment]
Hello @jublo   it seems the 502 error is appearing again,  any idea?  thanks !!
