### ISSUE TITLE
https://api.jublo.net/codebird/oauth2/token not responding

### ISSUE THREAD

**Issue by loveblank** [jublonet/codebird-js#92]
https://api.jublo.net/codebird/oauth2/token is unreachable

**Comment by Grabes** [comment]
I am also having the same problem. Trying to access https://api.jublo.net/codebird/oauth2/token returns a 502 error.

**Comment by jublo** [comment]
Does this work for you now, @loveblank and @Grabes?

**Comment by Grabes** [comment]
Yes it is working now but the proxy went down for about 12 hours and it cost us. How could we build our own proxy service for this? Would you be able to share some of the code?

**Comment by joshuaatkins** [comment]
Hi @Grabes, you can see our proxy code here https://github.com/jublonet/codebird-cors-proxy. Over the past month we have invested alot of money, and are going to invest more in improving the redundancy and performance of this proxy. Having 100% uptime over the past 14 days.

**Comment by Grabes** [comment]
We appreciate the support and have noticed an increase in speed over the last week. Thanks!

**Comment by jublo** [comment]
Thanks @Grabes for your feedback. We will leave this issue open for some time and close it if no additional outages occur.

**Comment by mrbellek** [comment]
It still doesn't work for me. I copied the example code word for word.
The request_token call to api.jublo.net/codebird/oauth still returns nothing.

**Comment by jublo** [comment]
Let's track this issue at #91.

**Comment by chinna-magapu** [comment]
Hi @joshuaatkins ,
https://api.jublo.net/codebird/oauth/request_token is not reachable , 
 Previously it was working fine. but now when iam Trying to access https://api.jublo.net/codebird/oauth/request_token returns a 502 error.

**Comment by vpaq** [comment]
I have the same problem than @chinna-magapu. Not reachable, and after few seconds it says: Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.jublo.net/codebird/oauth2/token. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by vpaq** [comment]
Any help would be appreciated ❤️

**Comment by jublo** [comment]
@vpaq We’re currently taking a look. If you want to, you can always run your own codebird proxy: https://github.com/jublonet/codebird-js#using-your-own-proxy-server

**Comment by vpaq** [comment]
It seems to be fixed, thank you @jublo
