### ISSUE TITLE
Unable to logout

### ISSUE THREAD

**Issue by Namib** [jublonet/codebird-js#94]
How can I log out from twitter? I cannot find any method to achieve this..please suggest. Thanks!

**Comment by jublo** [comment]
How about just deleting the access token and its secret from your storage and reinitializing the codebird class?

**Comment by Namib** [comment]
Thanks for the reply. Yes, I will try this. But it would be simple if a logout() method is added in the .js itself. Just a suggestion. :)

**Comment by jublo** [comment]
Thanks @Namib for your suggestion.  We have added #96 to our backlog.  Please send us an e-mail to support@jublo.net so we may add you to the codebird-js news list (low frequency, only for new releases and important service announcements). Don't worry—we have spam as much as you do.

**Comment by Namib** [comment]
No problem. Thanks for considering the suggestion and adding it to backlog. Looking forward to hearing from you on mail :)
