### ISSUE TITLE
Please release 2.6.0 and push through bower

### ISSUE THREAD

**Issue by rojobo** [jublonet/codebird-js#95]
HI GUYS,

RUNNING A BOWER UPDATE WILL NOT UPDATE TO 2.6
 DIRECTLY SETTING THE BOWER.JSON FILE TO 2.6-DEV

I GET:

Available versions: 2.5.0, 2.5.0-rc.2, 2.5.0-rc.1, 2.5.0-alpha1.1, 2.5.0-alpha.1, 2.4.3, 2.4.2, 2.4.1, 2.4.0, 2.3.3, 2.3.2, 2.3.1, 2.3.0, 2.2.3, 2.2.3-internal, 2.2.2, 2.2.2-internal, 2.2.1, 2.2.0
dev6@natboucher:/home/projects/hts_app$ bower install codebird --save-dev
bower codebird#~2.6.0-dev   not-cached git://github.com/mynetx/codebird-js.git#~2.6.0-dev
bower codebird#~2.6.0-dev      resolve git://github.com/mynetx/codebird-js.git#~2.6.0-dev
bower codebird#*                cached git://github.com/mynetx/codebird-js.git#2.5.0
bower codebird#*              validate 2.5.0 against git://github.com/mynetx/codebird-js.git#*
bower codebird#~2.6.0-dev   not-cached git://github.com/mynetx/codebird-js.git#~2.6.0-dev
bower codebird#~2.6.0-dev      resolve git://github.com/mynetx/codebird-js.git#~2.6.0-dev
bower codebird#~2.6.0-dev ENORESTARGET No tag found that was able to satisfy ~2.6.0-dev

**Comment by jublo** [comment]
`2.6-dev` is not a version (that could be accessed via bower), but the current **dev**elopment branch.
That being said, have a look at [codebird-js 2.6.0-rc.1](https://github.com/jublonet/codebird-js/releases/tag/2.6.0-rc.1), a prerelease version of the upcoming 2.6.0.

For your convenience, codebird-js 2.6.0-rc.1 is also available on Bower and NPM.

**Comment by rojobo** [comment]
@jublo always prompt and kind thanks a lot

**Comment by jublo** [comment]
@rojobo You're welcome!  Why not recommend us on Twitter? :bird:
