### ISSUE TITLE
Calling media/upload with incorrect Content-Type

### ISSUE THREAD

**Issue by araskin** [jublonet/codebird-js#99]
Hi,

I am using callBird to call media/upload end point. However, I noticed that the content-type is being set as application/x-www-form-urlencoded and according to https://dev.twitter.com/rest/reference/post/media/upload it should be set to multipart/form-data

Is this a bug or am I doing something wrong?

**Comment by jublo** [comment]
Hi Alon,

have some sample code that you're using to upload your image?

**Comment by jublo** [comment]
Also, which codebird version are you running?

**Comment by jublo** [comment]
See #104.
